### ISSUE TITLE
Support defining command aliases in a configuration file

### ISSUE THREAD

**Issue by jwodder** [jwodder/forall#37]
E.g.:

```toml
[command.rsclean]
root = "~/work/rust"
language = "Rust"
filter = "test -d target"
run = ["cargo", "clean"]
```

Support appending arguments from the command line to the `run` value.
